# inter-annotator agreement

Manual check by Yu-Chen & Shakshi. 
Data stored in the folder: /1125 models/17_data/*sample_labeled.csv*

In [1]:
from sklearn.metrics import cohen_kappa_score, confusion_matrix
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
label_check = pd.read_csv('sydneysiege/17 saved_models/sample_model_targetlabel-2.csv',header=0,encoding='utf-8')

In [3]:
label_check

src_tweet_id  reply_tweet_id  reply_user_id  \
0   544445364322197504    5.444970e+17      347462394   
1   544280765111218176    5.442810e+17      301910658   
2   544462912644214785    5.444636e+17     2591370314   
3   544390903839088640    5.443921e+17      309655617   
4   544297827258888192    5.443050e+17      134833919   
..                 ...             ...            ...   
95  544273427075710976    5.442737e+17       21159892   
96  544362279006113792    5.443648e+17      378973056   
97  544300178443100160    5.443045e+17      291763454   
98  544430771688439808    5.444344e+17        5402612   
99  544317438079139841    5.443275e+17     1100048125   

                        reply_date  rumorlabel reply_sentiment  \
0   Mon Dec 15 14:19:29 +0000 2014           1        Negative   
1   Mon Dec 15 00:01:06 +0000 2014           1         Neutral   
2   Mon Dec 15 12:06:47 +0000 2014           1        Negative   
3   Mon Dec 15 07:22:44 +0000 2014           1        Positive   
4   Mon Dec 15 01:36:47 +0000 2014           1        Negative   
..                             ...         ...             ...   
95  Sun Dec 14 23:32:27 +0000 2014           1        Positive   
96  Mon Dec 15 05:34:09 +0000 2014           1         Neutral   
97  Mon Dec 15 01:34:33 +0000 2014           1        Positive   
98  Mon Dec 15 10:10:51 +0000 2014           1        Negative   
99  Mon Dec 15 03:06:14 +0000 2014           1        Negative   

                                          reply_tweet  \
0   @bathsaltsniall @_Maleven but no one is stonin...   
1                          @Reuters took your time...   
2   @Softsaint @GMA good they got out shame this i...   
3   @anthea_bailey @SkyNewsBreak they said they es...   
4   @PamelaGeller Today @FareedZakaria called out ...   
..                                                ...   
95  @NickKristof The Sydney Morning Herald – @smh ...   
96  @cnnbrk We know, we're watching it on ABC! I u...   
97  @Busty1956 @MaajidNawaz this has nothing to do...   
98  Australian Muslim groups condemn #SydneySiege ...   
99  @PMOnAir Paul, are we possibly putting hostage...   

                                     cleaned_reply_tw  Yu-Chen  Shakshi  \
0                          no one stone baby move one        0        0   
1                                           take time        0        0   
2                             good get shame happenng        0        0   
3                                          say escape        0        0   
4   today call australia worst offender wrt global...        0        0   
..                                                ...      ...      ...   
95       sydney morning herald daily paper sydney fyi        0        0   
96  know watch abc understand guy broadcast someth...        0        0   
97  nothing muslims stop try conflate two issue to...        0        0   
98  australian muslim group condemn sydneysiege st...        0        0   
99  paul possibly put hostages risk discuss im con...        0        0   

    targetlabel  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
95            0  
96            0  
97            1  
98            1  
99            0  

[100 rows x 11 columns]

In [4]:
confusion_matrix(label_check['Yu-Chen'],label_check['Shakshi'])

array([[84,  0],
       [ 4, 12]], dtype=int64)

In [5]:
cohen_kappa_score(label_check['Yu-Chen'],label_check['Shakshi'])

0.8344370860927153

## Model vs Annotators

In [6]:
confusion_matrix(label_check['Shakshi'],label_check['targetlabel'])

array([[71, 17],
       [ 4,  8]], dtype=int64)

In [7]:
confusion_matrix(label_check['Yu-Chen'],label_check['targetlabel'])

array([[67, 17],
       [ 8,  8]], dtype=int64)

In [8]:
cohen_kappa_score(label_check['Yu-Chen'],label_check['targetlabel'])

0.24242424242424243

In [9]:
cohen_kappa_score(label_check['Shakshi'],label_check['targetlabel'])

0.32258064516129037